from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, get_object_or_404
from django.views.static import serve
from children import views as chviews
from general import views as gviews


urlpatterns = [

    path('children/dashboardcontent', chviews.dashboardcontent,
         name='children_dashboard_content'),
    path('children/unsuspend', chviews.unsuspend,
         name='children_unsuspend'),
    path('children/eventregistration/<str:eventid>/<str:hostedeventid>',
         chviews.eventregistration, name='children_event_registration'),
     path('children/classpupils/<str:childage>',
         chviews.pupilsperclass, name='class_pupils'),
    path('children/change_private_number', chviews.changeprivatenumber,
         name='change_private_number'),
    path('children/information_desk_content/<str:content>/<str:cid>',
         chviews.informationdeskcontent, name='children_information_desk_content'),
    path('children/add_dependant', chviews.adddependant,
         name='children_add_dependant'),
    path('children/add_guardian', chviews.addguardian,name='children_add_guardian'),
        path('children/add_parent', chviews.addparent,name='children_add_parent'),
         path('children/change_availability/<str:dependantid>/<str:status>',
         chviews.changeavailabilitystatus, name='children_change_availability'),
         path('children/change_guardian_status/<str:memberid>/<str:status>',
         chviews.changeguardianstatus, name='children_change_guardian_status'),
    path('children/edit_dependant/<str:dependantid>',
         chviews.editdependant, name='children_edit_dependant'),
    path('children/register_dependant/<str:eventid>/<str:hostedeventid>/<str:memberid>',
         chviews.registerdependant, name='children_register_dependant'),
    path('children/unregister_dependant/<str:eventid>/<str:hostedeventid>/<str:memberid>',
         chviews.unregisterdependant, name='children_unregister_dependant'),
    path('children/dependant_verification/<str:eventid>/<str:hostedeventid>',
         chviews.pickupverification, name='children_pickup_verification'),
    path('children/register_all_dependants/<str:eventid>/<str:hostedeventid>/<str:phonenumber>',
         chviews.registeralldependants, name='children_register_all_dependants'),
    path('children/change_status/verify/<str:eventid>/<str:hostedeventid>/<str:dependantid>/<str:action>/',
         chviews.changeregistrastionstatuschoice, name='children_verify_change_registration_status'),
    path('children/change_status/<str:eventid>/<str:hostedeventid>/<str:dependantid>/<str:memberid>/<str:status>/',
         chviews.changeregistrationstatus, name='children_change_registration_status'),
    path('children/register_dependant_choice/<str:eventid>/<str:hostedeventid>',
         chviews.registerdependentchoice, name='children_register_dependant_choice'),
    path('children/accept_parentage', chviews.acceptparentage,
         name='children_accept_parentage'),
    path('children/verifyevent', chviews.verifyevent,
         name='children_verify_event'),
    path('children/profile', chviews.myprofile, name='children_profile'),
    path('children/announcements', chviews.announcements,
         name='children_announcements'),
    path('children/parent', chviews.parenttab, name='children_parent_tab'),
    path('children/events', chviews.eventtab, name='children_event_tab'),
    path('children/home', chviews.hometab, name='children_home_tab'),
    path('children/announcement/<str:announcementid>',
         chviews.announcementdetails, name='children_announcement_details'),
    path('children/videos', chviews.videos, name='children_videos'),
    path('children/myevents', chviews.myevents, name='children_my_events'),
    path('children/hostevent/<str:eventid>',
         chviews.hostevent, name='children_host_event'),

    path('children/childrencreateevent',
         chviews.createevent, name='children_create_event'),
    path('children/editevent/<str:eventid>/<str:hostedeventid>',
         chviews.edithostedevent, name='children_edit_hosted_event'),
    path('children/editevent/<str:eventid>',
         chviews.editevent, name='children_edit_event'),
    path('children/editticket/<str:eventid>/<str:hostedeventid>/<str:ticketid>',
         chviews.editticket, name='children_edit_hosted_event_ticket'),
    path('children/editarrangement/<str:eventid>/<str:hostedeventid>/<str:arrangementid>',
         chviews.editarrangement, name='children_edit_hosted_event_arrangement'),
    path('children/deletearrangement/<str:eventid>/<str:hostedeventid>/<str:arrangementid>',
         chviews.deletearrangement, name='children_delete_hosted_event_arrangement'),
    path('children/deleteticket/<str:eventid>/<str:ticketid>/<str:hostedeventid>',
         chviews.deleteticket, name='children_delete_hosted_event_ticket'),
    path('children/createeventticket/<str:eventid>/<str:hostedeventid>/<str:dayid>/<str:action>',
         chviews.createeventticket, name='children_create_hosted_event_ticket'),
    path('children/createeventday/<str:eventid>/<str:hostedeventid>/<str:scope>/<str:action>',
         chviews.createeventday, name='children_create_hosted_event_day'),
    path('children/deleteeventday/<str:eventid>/<str:hostedeventid>/<str:dayid>',
         chviews.deleteeventday, name='children_delete_hosted_event_day'),
    path('children/editeventday/<str:eventid>/<str:hostedeventid>/<str:dayid>',
         chviews.editeventday, name='children_edit_hosted_event_day'),
    path('children/eventdaydetails/<str:eventid>/<str:hostedeventid>/<str:dayid>',
         chviews.eventdaydetails, name='children_event_day_details'),
    path('children/eventdayregistration/<str:eventid>/<str:hostedeventid>/<str:dayid>',
         chviews.eventdayregistration, name='children_event_day_registration'),
    path('children/createeventarrangement/<str:eventid>/<str:hostedeventid>/<str:dayid>/<str:action>',
         chviews.createeventarrangement, name='children_create_hosted_event_arrangement'),
    path('children/manageevent/<str:eventid>/<str:hostedeventid>',
         chviews.manageevent, name='children_manage_event'),
    path('children/publishevent/<str:eventid>/<str:hostedeventid>',
         chviews.publishevent, name='children_publish_hosted_event'),

    path('children/unpublishevent/<str:eventid>/<str:hostedeventid>',
         chviews.unpublishevent, name='children_unpublish_hosted_event'),
    path('children/viewevent/<str:eventid>',
         chviews.viewevent, name='children_view_event'),
    path('children/event/qrcode/<str:eventid>/<str:hostedeventid>',
         chviews.eventqrcode, name='children_event_qrcode'),
    path('children/event/attendee/qrcode/<str:eventid>',
         chviews.attendeeqrcode, name='children_attendee_qrcode'),
    path('children/eventdetails/<str:eventid>/<str:hostedeventid>',
         chviews.eventdetails, name='children_event_details'),
    path('children/event_qrcode_attendance/<str:eventid>/<str:hostedeventid>',
         chviews.attendeeqrcverification, name='children_event_qrcode_attendance'),
    path('children/boughtdayticket/<str:eventid>/<str:hostedeventid>/<str:ticketid>/<str:dayid>',
         chviews.boughtdayticket, name='children_bought_day_ticket'),

    path('children/boughtticket/<str:eventid>/<str:hostedeventid>/<str:ticketid>/<str:dayid>',
         chviews.boughtticket, name='children_bought_ticket'),
    path('children/buyticket/<str:eventid>/<str:hostedeventid>',
         chviews.buyticket, name='children_buy_ticket'),
    path('children/host_qrcode_verification/<str:eventid>/<str:hostedeventid>',
         chviews.hostqrcverification, name='children_host_qrcode_verification'),

    path('children/events', chviews.events, name='children_events'),

    path('children/update_profile', chviews.updateprofile,
         name='children_update_profile'),

    url('activate-account', gviews.activate, name='children_activate_account'),
    url('createwallet', gviews.createaccounts, name='children_create_accounts'),
    url('resendactivationcode', gviews.resendactivationcode,
        name='children_resend_activation_code'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
